### ISSUE TITLE
Request for release new version

### ISSUE THREAD

**Issue by k-okada** [rdiankov/collada-dom#16]

**Comment by k-okada** [comment]
@rdiankov could you release new version of collada-dom on ppa so at ha we can easily use them as deb file?

Thanks in advance!!

**Comment by rdiankov** [comment]
i'm guessing a version with the liburiparser library right?
i'll try to kickoff the job

**Comment by k-okada** [comment]
> i'm guessing a version with the liburiparser library right?

yes, that should be version 2.4.4, I think.

**Comment by 130s** [comment]
Ping @rdiankov thanks!

**Comment by 130s** [comment]
@rdiankov If you get to have some to make a new release that'll be appreciated as always. Thank you!

**Comment by rdiankov** [comment]
sorry for being late. can you stop by my office this weekend on Oct 3 to talk about this and how to maintain deb packages? we are at:

113-0033
東京都 文京区本郷 4-8-13
TSKビル１F

thanks

**Comment by k-okada** [comment]
hi, can I visit your office on this evening, 5pm or 6pm?

--
◉ Kei Okada

**Comment by k-okada** [comment]
@rdiankov thanks !! I have confirmed testing version working well and copies to the release repository
https://launchpad.net/~openrave/+archive/ubuntu/release/+packages
