### ISSUE TITLE
Mixed lineends in many source files

### ISSUE THREAD

**Issue by wookey** [rdiankov/collada-dom#17]
The source for this software has a large number of files which have mixed dos and unix linefeeds, which whilst mostly harmless is definitely wrong. Most of the problem is that the licence header has DOS lineends, whilst the rest of the file is unix (although not in every file for some reason). But there are also files when edits such as new functions or lines have been added with DOS lineends, presumably by someone using an editor too stupid to get it right. 

Attached is a patch to fix them all up. 

There are also some files which are entirely DOS lineends, which is OK, but it might make sense to make the whole codebase consistent, which is a trivial matter of running 
find . -type f | xargs dos2unix
It is possible that there is a good reason for some of the test xml files to have DOS lineends(?), in which case leave them alone.

Hmm. this issue tracker doesn't allow attaching patches. The file is here: http://anonscm.debian.org/cgit/debian-science/packages/collada-dom.git/diff/debian/patches/linefeed-fixup.patch?id=9652330772f7e441b423a41d88f52c245569c049

**Comment by rdiankov** [comment]
thanks for the patch! i just applied it:

https://github.com/rdiankov/collada-dom/commit/94433cd7445db88420cd239e6a3d87bcbd2883cc
