### ISSUE TITLE
How to use colladadom in multithread to read dae files

### ISSUE THREAD

**Issue by mingweiLIU** [rdiankov/collada-dom#23]
Hi, I am using colladadom to read dae files, I have built it only with collada14dom option, and the environment is Visual Studio2015 under windows, I have used multithreads to read different files, while encounter "this-> _type is nullptr" at 
![default](https://cloud.githubusercontent.com/assets/11702952/15446078/ad9f7d70-1f45-11e6-8eb1-4c91d48e1281.jpg) 

my test codes are simple:
`#include "stdafx.h"
#include thread
#include "dae.h"
#include vector

static void test(int i)
{
	if (0==i)
	{
		DAE dae;		dae.open("a.dae");
	} 
	else
	{
		DAE dae1;		dae1.open("b.dae");
	}
}

using namespace std;
int main()
{
	vector<thread> tests;
	for (int i=0;i<2;i++)
	{
		tests.push_back(thread(test,i));
	}

	for (auto & k:tests)
	{
		k.join();
	}
	return 0;
}`
Could you give me some advises about how could I properly use colladadom in  multithreads ?

**Comment by rdiankov** [comment]
i think DAE object was meant to be created once per process. Can you create it once and then continue opening different files with the same global object in different threads?

**Comment by mingweiLIU** [comment]
It is a great suggustion, after changing the Dae object to be a global one the code works. Since the DAE object should not to be created more than once, is that to say a static one will still work? Finally I used a static variable in my code and fixed it up. Thanks!
