### ISSUE TITLE
Please tag release 2.5

### ISSUE THREAD

**Issue by morxa** [rdiankov/collada-dom#28]
So it seems like 2.5 is already released but not tagged as a release, as already mentioned in rdiankov/openrave#428. 

Can you please add a tag? This allows me to update the Fedora package without modifying the release scripts, which expect properly tagged releases.

Also, I get automatic notifications for tagged releases, so even if it looks like a technical detail, they are actually very useful for downstream packaging.

Thanks!

**Comment by rdiankov** [comment]
tagged, thanks!

**Comment by morxa** [comment]
Thanks! I pushed the update to Fedora rawhide.
