### ISSUE TITLE
zip-related failure when building on Mac

### ISSUE THREAD

**Issue by jdmuys** [rdiankov/collada-dom#3]
Following the instructions given, the "make" stage fails when building on Mac: functions such as fopen64 fail to compile.

The terminal output is:

/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:115:16: error: use of undeclared identifier 'Dfseeko64'; did you mean 'fseeko'?
        file = fopen64((const char*)filename, mode_fopen);
               ^
<command line>:2:24: note: expanded from here
# define fopen64 fopen -Dfseeko64=fseeko -Dfseek64=fseek -Dftell64=ftell -Dftello64=ftello

```
                   ^
```

/usr/include/stdio.h:418:6: note: 'fseeko' declared here
int      fseeko(FILE _, off_t, int);
         ^
/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:115:16: error: 'FILE *(_)(const char _restrict, const char *restrict)' and
      'int (_)(FILE _, off_t, int)' are not pointers to compatible types
        file = fopen64((const char_)filename, mode_fopen);
               ^~~~~~~
<command line>:2:23: note: expanded from here
# define fopen64 fopen -Dfseeko64=fseeko -Dfseek64=fseek -Dftell64=ftell -Dftello64=ftello

```
            ~~~~~ ^~~~~~~~~~
```

/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:115:16: error: use of undeclared identifier 'Dfseek64'
<command line>:2:42: note: expanded from here
# define fopen64 fopen -Dfseeko64=fseeko -Dfseek64=fseek -Dftell64=ftell -Dftello64=ftello

```
                                     ^
```

/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:115:16: error: use of undeclared identifier 'Dftell64'
<command line>:2:58: note: expanded from here
# define fopen64 fopen -Dfseeko64=fseeko -Dfseek64=fseek -Dftell64=ftell -Dftello64=ftello

```
                                                     ^
```

/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:115:16: error: use of undeclared identifier 'Dftello64'; did you mean 'ftello'?
<command line>:2:74: note: expanded from here
# define fopen64 fopen -Dfseeko64=fseeko -Dfseek64=fseek -Dftell64=ftell -Dftello64=ftello

```
                                                                     ^
```

/usr/include/stdio.h:419:8: note: 'ftello' declared here
off_t    ftello(FILE _);
         ^
/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:115:16: error: 'long (_)(FILE _)' and 'off_t (_)(FILE _)' are not pointers to
      compatible types
        file = fopen64((const char_)filename, mode_fopen);
               ^~~~~~~
<command line>:2:73: note: expanded from here
# define fopen64 fopen -Dfseeko64=fseeko -Dfseek64=fseek -Dftell64=ftell -Dftello64=ftello

```
                                                              ~~~~~ ^~~~~~~~~~
```

/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:115:47: error: too many arguments to function call, expected 1, have 2
        file = fopen64((const char_)filename, mode_fopen);
               ~~~~~~~                        ^~~~~~~~~~
/usr/include/stdio.h:419:1: note: 'ftello' declared here
off_t    ftello(FILE *);
^
/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:145:11: warning: implicit declaration of function 'ftello64' is invalid in C99
      [-Wimplicit-function-declaration]
    ret = ftello64((FILE *)stream);
          ^
/Development/Collada/collada-dom/dom/external-libs/minizip-1.1/ioapi.c:191:8: warning: implicit declaration of function 'fseeko64' is invalid in C99
      [-Wimplicit-function-declaration]
    if(fseeko64((FILE *)stream, offset, fseek_origin) != 0)
       ^
2 warnings and 7 errors generated.
make[2]: *_\* [dom/external-libs/minizip-1.1/CMakeFiles/minizip.dir/ioapi.c.o] Error 1
make[1]: **\* [dom/external-libs/minizip-1.1/CMakeFiles/minizip.dir/all] Error 2
make: **\* [all] Error 2

Note: the workaround I found is to add the following line at the top of ioapi.h:
# define USE_FILE32API

With that workaround, I get many annoying macro redefined warnings, but no error.

**Comment by apjanke** [comment]
You can also just remove the quotes if you want to keep it on one line.

```
add_definitions(-Dfopen64=fopen -Dfseeko64=fseeko -Dfseek64=fseek -Dftell64=ftell -Dftello64=ftello)
```

That's how Mac Homebrew's collada-dom formula [is handling it](https://github.com/Homebrew/homebrew/commit/d3dea6e34af5b61396b39b48c7ac56b7ba1fff54).
